export interface KeyedStore<T extends { id: string }> {
  list(): T[];
  get(id: string): T | undefined;
  create(record: T): T;
  replace(id: string, build: (existing: T) => T): T | undefined;
  patch(id: string, patch: Partial<Omit<T, "id">>): T | undefined;
  remove(id: string): boolean;
  reset(records: T[]): void;
}

/**
 * A generic string-keyed in-memory store, for resources whose id (a slug or a UUID) is assigned by
 * the caller rather than generated by the store itself — unlike `createInMemoryStore`'s numeric
 * auto-increment ids, `create()` here takes a fully-formed record (research.md).
 */
export function createKeyedStore<T extends { id: string }>(): KeyedStore<T> {
  let records = new Map<string, T>();

  return {
    list(): T[] {
      return Array.from(records.values());
    },

    get(id: string): T | undefined {
      return records.get(id);
    },

    create(record: T): T {
      records.set(record.id, record);
      return record;
    },

    replace(id: string, build: (existing: T) => T): T | undefined {
      const existing = records.get(id);
      if (!existing) return undefined;
      const updated = build(existing);
      records.set(id, updated);
      return updated;
    },

    patch(id: string, patch: Partial<Omit<T, "id">>): T | undefined {
      const existing = records.get(id);
      if (!existing) return undefined;
      const updated = { ...existing, ...patch, id: existing.id };
      records.set(id, updated);
      return updated;
    },

    remove(id: string): boolean {
      return records.delete(id);
    },

    reset(seedRecords: T[]): void {
      records = new Map(seedRecords.map((record) => [record.id, record]));
    },
  };
}
